export const DIMENSIONS = {
  CANVAS_WIDTH: 500,
  CANVAS_HEIGHT: 500,
};

export const LANTERN_BRIGHTNESS_DECREASE_RATE = 1;
export const BLOOD_PARTICLE_TIMEOUT = 5000;
export const WEAPON_HEIGHT_AND_WIDTH = 50;
export const BOSS_HEIGHT_AND_WIDTH = 150;
export const BOSS_ATTACK_DAMAGE = 2;
export const BOSS_DEFAULT_HEALTH = 80;
export const BOSS_MOVEMENT_SPEED = 2;
export const GOBLIN_SPAWN_TIME = 1000;
export const PLAYER_MOVEMENT_SPEED = 4;
export const PLAYER_HEALTH = 100;
export const PLAYER_STAMINA = 100;
export const LIGHT_OF_BLESSINGS_DURATION = 5000;
export const ENEMY_REACTION_DISTANCE = 1000;
export const LANTERN_BRIGHTNESS_RADIUS = 250;
