export const voice = {
    diegoblins: { audio: new Audio("./assets/sound/voice/dieyougoblins.mp3"), hasPlayed: false, canPlayAgain: true},
    howsharp: { audio: new Audio("./assets/sound/voice/howsharpt.mp3"), hasPlayed: false, canPlayAgain: true},
    idontfeelsogood: { audio: new Audio("./assets/sound/voice/idontfeelsogood.mp3"), hasPlayed: false, canPlayAgain: true},
    isthatboss: { audio: new Audio("./assets/sound/voice/isthatthegoblinboss.mp3"), hasPlayed: false, canPlayAgain: false},
    ithurts: { audio: new Audio("./assets/sound/voice/ithurts.mp3"), hasPlayed: false, canPlayAgain: true},
    lanternrunningout: { audio: new Audio("./assets/sound/voice/lanternisrunningout.mp3"), hasPlayed: false, canPlayAgain: true},
    letsstartkilling: { audio: new Audio("./assets/sound/voice/letsstartkillinggoblins.mp3"), hasPlayed: false, canPlayAgain: true},
    notready: { audio: new Audio("./assets/sound/voice/notreadyyet.mp3"), hasPlayed: false, canPlayAgain: true},
    outofammo: { audio: new Audio("./assets/sound/voice/outofammo.mp3"), hasPlayed: false, canPlayAgain: true},
    outoffuel: { audio: new Audio("./assets/sound/voice/outoflanternfuel.mp3"), hasPlayed: false, canPlayAgain: true},
    outofmedkit: { audio: new Audio("./assets/sound/voice/outofmedkit.mp3"), hasPlayed: false, canPlayAgain: true},
    wedidit: { audio: new Audio("./assets/sound/voice/yaywedidit.mp3"), hasPlayed: false, canPlayAgain: false},
    axesound: { audio: new Audio("./assets/sound/axesound.mp3"), hasPlayed: false, canPlayAgain: true},
    breathofdragon: { audio: new Audio("./assets/sound/voice/breathofdragon.mp3"), hasPlayed: false, canPlayAgain: true},
    hmmaxe: { audio: new Audio("./assets/sound/voice/hmmaxe.mp3"), hasPlayed: false, canPlayAgain: true},
    gunfire: { audio: new Audio("./assets/sound/gunfire.mp3"), hasPlayed: false, canPlayAgain: true},
    iamtired: { audio: new Audio("./assets/sound/voice/iamtired.mp3"), hasPlayed: false, canPlayAgain: true},
    lightofblessings: { audio: new Audio("./assets/sound/voice/lightofblessings.mp3"), hasPlayed: false, canPlayAgain: true},
    yaygun: { audio: new Audio("./assets/sound/voice/yaygun.mp3"), hasPlayed: false, canPlayAgain: true},
    walk: { audio: new Audio("./assets/sound/walk.mp3"), hasPlayed: false, canPlayAgain: true},
    run: { audio: new Audio("./assets/sound/walk.mp3"), hasPlayed: false, canPlayAgain: true},
    zombiegrunt: { audio: new Audio("./assets/sound/zombiegrunt.mp3"), hasPlayed: false, canPlayAgain: true},
    wind: { audio: new Audio("./assets/sound/wind.mp3"), hasPlayed: false, canPlayAgain: true},

}